import {
  mdiAccountMultiple,
  mdiAlert,
  mdiArrowBottomLeft,
  mdiArrowDown,
  mdiArrowRight,
  mdiArrowRightTop,
  mdiArrowUp,
  mdiBackspaceOutline,
  mdiBank,
  mdiCalendar,
  mdiCashMultiple,
  mdiChartBar,
  mdiChartPie,
  mdiCheck,
  mdiChevronDown,
  mdiChevronUp,
  mdiClose,
  mdiCog,
  mdiCreditCardOutline,
  mdiEye,
  mdiEyeOff,
  mdiFolder,
  mdiGoogleAnalytics,
  mdiInformation,
  mdiLabel,
  mdiLogin,
  mdiLogout,
  mdiOpenInNew,
  mdiPencil,
  mdiPhone,
  mdiPiggyBank,
  mdiPlus,
  mdiPlusBox,
  mdiShape,
  mdiSwapVertical,
  mdiSwapVerticalBold,
  mdiTrashCanOutline,
  mdiUpdate,
} from '@mdi/js';

const ICONS = {
  ALERT: mdiAlert,
  ANALYTICS: mdiGoogleAnalytics,
  ARROW_BOTTOM_LEFT: mdiArrowBottomLeft,
  ARROW_DOWN: mdiArrowDown,
  ARROW_RIGHT: mdiArrowRight,
  ARROW_RIGHT_TOP: mdiArrowRightTop,
  ARROW_UP: mdiArrowUp,
  BACKSPACE: mdiBackspaceOutline,
  BANK: mdiBank,
  CASH: mdiCashMultiple,
  CHART_BAR: mdiChartBar,
  CHART_PIE: mdiChartPie,
  CALENDAR: mdiCalendar,
  COG: mdiCog,
  CHECK: mdiCheck,
  CHEVRON_DOWN: mdiChevronDown,
  CHEVRON_UP: mdiChevronUp,
  CLOSE: mdiClose,
  CREDIT_CARD: mdiCreditCardOutline,
  EYE: mdiEye,
  EYE_OFF: mdiEyeOff,
  FOLDER: mdiFolder,
  INFO: mdiInformation,
  LABEL: mdiLabel,
  LOGIN: mdiLogin,
  LOGOUT: mdiLogout,
  OPEN_IN_NEW: mdiOpenInNew,
  PENCIL: mdiPencil,
  PHONE: mdiPhone,
  PIGGY_BANK: mdiPiggyBank,
  PLUS: mdiPlus,
  PLUS_BOX: mdiPlusBox,
  SHARE: mdiAccountMultiple,
  SHAPE: mdiShape,
  SWAP_VERTICAL: mdiSwapVertical,
  SWAP_VERTICAL_BOLD: mdiSwapVerticalBold,
  TRASH: mdiTrashCanOutline,
  UPDATE: mdiUpdate,
};

export default defineNuxtPlugin((nuxtApp) => {
  return {
    provide: { ICONS },
  };
});
